standardnotes/mobile

README.md
Not much. Check the diff and you'll see what I mean.
=> Fix web address at README

src/lib/userPrefsManager.js, src/screens/ComponentView.js
Original issue: #181 
Adds a "Don't show again" button that closes the alert and does not shows it again.
=> Option to "Don't show again" for alert that appears on Android < 7 regarding web editors

android/app/gradle/wrapper/gradle-wrapper.properties
...else the F-Droid build fails
=> Update gradle here too

.eslintrc, .eslintrc.js, .gitmodules, .prettierrc, android/app/build.gradle, android/app/src/main/java/com/standardnotes/MainApplication.java, android/settings.gradle, ios/Podfile, ios/Podfile.lock, package-lock.json, package.json, src/App.js, src/components/ThemedComponent.js, src/lib/keysManager.js, src/lib/userPrefsManager.js, src/lib/utils.js, src/screens/Authentication/Authenticate.js, src/screens/Authentication/Sources/AuthenticationSource.js, src/screens/Authentication/Sources/AuthenticationSourceAccountPassword.js, src/screens/Authentication/Sources/AuthenticationSourceBiometric.js, src/screens/Authentication/Sources/AuthenticationSourceLocalPasscode.js, src/screens/ComponentView.js, src/screens/Settings/Sections/PasscodeSection.js, src/screens/Settings/Settings.js, src/screens/SideMenu/MainSideMenu.js, src/screens/SideMenu/SideMenuManager.js, src/style/StyleKit.js, src/style/ThemeManager.js, src/style/Util/CSSParser.js
Switches to new Android Biometric API for devices that support it. Also includes a couple bug fixes that allows successful attempts to always unlock the app (even after several failed attempts).
=> Android Biometric support

package.json, src/App.tsx, src/lib/InstallationService.ts, src/lib/application.ts, src/lib/applicationGroup.ts, src/lib/interface.ts, src/screens/Settings/Sections/AuthSection.tsx, yarn.lock
Reverts standardnotes/mobile#284
=> Revert "feat: snjs application groups"

README.md
Added shields for release, license, Slack, and Twitter
=> Update README.md with shields [skip ci]

package.json, yarn.lock
This will:
- Require authentication when disabling biometrics
- Provide placeholders every time a challenge with account password or application passcode gets emitted
No changes needed on the mobile side :)
=> chore(deps): upgrade snjs

package.json, src/lib/snjs_helper_hooks.ts, src/lib/utils.ts, src/screens/Settings/Sections/PasscodeSection.styled.ts, src/screens/Settings/Sections/PasscodeSection.tsx, yarn.lock
Implement ability to clear protections session, based on Web implementation (https://github.com/standardnotes/web/commit/badff1568d6181909caa06c4546c93b75dcba83b)
=> Clear protections session

package.json, src/AppStack.tsx, src/components/Button.tsx, src/components/Chip.tsx, src/lib/snjs_helper_hooks.ts, src/screens/Notes/NoteCell.tsx, src/screens/Notes/NoteList.styled.ts, src/screens/Notes/NoteList.tsx, src/screens/Notes/Notes.tsx, src/screens/SideMenu/NoteSideMenu.tsx, src/screens/ViewProtectedNote/ViewProtectedNote.styled.ts, src/screens/ViewProtectedNote/ViewProtectedNote.tsx, src/screens/screens.ts, yarn.lock
- Added Include Protected Contents, Archived and Trashed search options
- Added View Protected Note screen shown when user opens a Protected note with no protection sources available
- Removed alert when trying to protect a note with no protection sources
=> Search options

ios/Podfile.lock, ios/StandardNotes.xcodeproj/project.pbxproj, src/lib/application.ts, src/lib/application_state.ts, src/screens/Compose/ComponentView.tsx, src/screens/Notes/Notes.tsx, src/screens/Settings/Sections/OptionsSection.tsx, src/screens/Settings/Sections/PreferencesSection.tsx, src/screens/SideMenu/MainSideMenu.tsx
Restores the active view as soon the saved tag is accessible (decrypted). This function used to fire too early when storage wasn't completely decrypted. Now it tries on every incremental load event.
=> Remember active tag on launch

.github/codeql/codeql-config.yml, .github/codeql/custom-queries/javascript/qlpack.yml, .github/workflows/codeql-analysis.yml, .gitignore, .prettierignore
Adds code analysis via CodeQL. The following queries are used:
- `security-and-quality`: queries from security-extended, plus maintainability and reliability queries
- custom queries located in [.github/codeql/custom-queries/javascript](https://github.com/standardnotes/mobile/tree/codeql-analysis/.github/codeql/custom-queries/javascript).
- code analysis for `java` will be introduced in another PR (this is currently broken).
See the [code scanning alerts generated by this PR](https://github.com/standardnotes/mobile/security/code-scanning?query=ref%3Arefs%2Fpull%2F414%2Fmerge).
=> chore: codeql analysis action 

src/screens/SideMenu/MainSideMenu.styled.ts, src/screens/SideMenu/MainSideMenu.tsx, src/screens/SideMenu/NoteSideMenu.styled.ts, src/screens/SideMenu/NoteSideMenu.tsx
Use a FlatList backed by a fixed array instead of a ScrollView
=> Fix DrawerLayout warnings

package.json, src/screens/Settings/Sections/OptionsSection.tsx, yarn.lock
=> feat: option to import backups

package.json, src/lib/application.ts, yarn.lock
Relates to: https://github.com/standardnotes/snjs/pull/319
=> feat: switch sign out to API v1

ios/Podfile.lock, package.json, src/screens/Compose/ComponentView.tsx, src/screens/Compose/Compose.styled.ts, src/screens/Compose/Compose.tsx, yarn.lock
Revert offline editors to avoid interrupting the usual release flow, and allow us to keep adjusting them on a separate feature branch.
=> feat: revert offline editors

package.json, src/screens/Compose/ComponentView.styled.ts, src/screens/Compose/ComponentView.tsx, yarn.lock
=> feat: show deprecation notice

package.json, src/screens/Notes/NoteCell.tsx
Asana task: https://app.asana.com/0/1199914526147392/1200015941119431
fixes #376
=> fix: no highlight when scrolling through note list

src/screens/Compose/Compose.tsx, src/screens/SideMenu/SideMenuHero.tsx
(Asana task: https://app.asana.com/0/1160981203938941/1198296778100997)
=> fix: note/tag count not updated properly when deleting all notes

android/app/src/main/AndroidManifest.xml, src/lib/backups_service.ts
(Asana task: https://app.asana.com/0/1199914526147392/1201175981326621)
=> fix: export backup to file on Android

android/build.gradle, package.json, src/App.tsx, src/lib/network_service.ts, src/screens/ManageSessions/ManageSessions.tsx, src/screens/Notes/NoteList.styled.ts, yarn.lock
(Asana task: https://app.asana.com/0/1199914526147392/1200241388937375)
=> feat: show message that user is offline when managing sessions

src/screens/Compose/ComponentView.tsx
(Asana task: https://app.asana.com/0/1160983365020104/1201443695251687)
=> fix: display message if using advanced editors on iOS < 11

android/app/src/main/AndroidManifest.xml
[Internal link](https://app.asana.com/0/1191872924317559/1201637211024569/)
---
fixes #530
=> fix: unable to open URLs on Android 11 and above

src/screens/Notes/NoteCell.styled.ts, src/screens/Notes/NoteCell.tsx
[Internal link](https://app.asana.com/0/1201611182420182/1201709907433958)
=> fix: correctly align note cell's left edge

src/screens/Notes/NoteCell.styled.ts, src/screens/Notes/NoteCell.tsx, src/screens/Notes/NoteCellIconFlags.tsx
[Internal link](https://app.asana.com/0/0/1201709907433958/1201771613974284/f)
=> fix: if note title is missing, move its contents to the title's position

android/app/build.gradle, ios/Podfile.lock, ios/StandardNotes.xcodeproj/project.pbxproj, package.json, src/lib/react_native_crypto.ts, yarn.lock
This is millions times faster 🎉
=> feat: use new JSI sodium implementation

package.json, src/screens/Compose/Compose.tsx
[Internal link](https://app.asana.com/0/1200588672119490/1201847548384300)
=> fix: allow copying locked note's title

src/screens/SideMenu/SideMenuSection.tsx
[Internal link](https://app.asana.com/0/1201653402817596/1201876460433544/f)
=> fix: change "Hidden" to "Tap to expand"

src/screens/SideMenu/NoteSideMenu.tsx
[Internal link](https://app.asana.com/0/0/1201978409281331/1202006193453524/f)
=> feat: add support for tag hierachy preference

src/hooks/useFiles.ts, src/lib/files_service.ts, src/screens/Compose/Compose.tsx, src/screens/ManageSessions/ManageSessions.tsx, src/screens/SideMenu/Files.tsx, src/screens/UploadedFilesList/UploadedFileItemAction.ts
[Internal link](https://app.asana.com/0/1200588672119490/1201931367397987)
=> feat: preview files

src/App.tsx, src/hooks/useFiles.ts, src/hooks/useSafeApplicationContext.ts, src/lib/snjs_helper_hooks.ts, src/screens/InputModal/FileInputModal.tsx, src/screens/Notes/Notes.tsx, src/screens/SideMenu/Files.tsx, src/screens/SideMenu/Listed.tsx, src/screens/SideMenu/NoteSideMenu.tsx, src/screens/SideMenu/TagSelectionList.tsx, src/screens/UploadedFilesList/UploadedFileItem.tsx, src/screens/UploadedFilesList/UploadedFilesList.tsx
[Internal link](https://app.asana.com/0/1200588672119490/1202042103062411)
=> refactor: remove `if (application)` checks when application is initialized for sure

src/lib/snjs_helper_hooks.ts, src/screens/Settings/Sections/ProtectionsSection.tsx
[Internal link](https://app.asana.com/0/1200588672119490/1202077369400283)
=> fix: update protections UI correctly after enabling protections

src/hooks/useFiles.ts
[Internal link](https://app.asana.com/0/1199942776723820/1202115110521082)
=> feat: implement files deletion

src/hooks/useFiles.ts, src/screens/ManageSessions/ManageSessions.tsx, src/screens/NoteHistory/NoteHistoryPreview.tsx, src/screens/Notes/NoteCell.tsx, src/screens/SideMenu/Listed.tsx, src/screens/SideMenu/MainSideMenu.tsx, src/screens/SideMenu/NoteSideMenu.tsx, src/screens/SideMenu/TagSelectionList.tsx, src/screens/UploadedFilesList/UploadedFilesList.tsx, src/style/custom_action_sheet.ts
[Internal link](https://app.asana.com/0/1199942776723820/1202138287571264)
=> fix: make the file name style bold in actions sheet

src/Hooks/useFiles.ts
[Internal link](https://app.asana.com/0/1199942776723820/1202138287571291)
=> feat: open the file after download when user taps on toast message

.prettierrc.js, ios/StandardNotes/Info.plist, ios/StandardNotesDev-Info.plist
[Internal link](https://app.asana.com/0/1200588672119490/1202162293027221)
=> fix: ask for microphone permission before capturing video

src/Screens/Authenticate/Authenticate.tsx
[Internal link](https://app.asana.com/0/1200588672119490/1202179964267392)
=> fix: don't wrap the word "Cancel" on authentication screen on ios

ios/Podfile.lock, package.json, src/Components/ToastWrapper.styled.ts, src/Components/ToastWrapper.tsx, src/Hooks/useFiles.ts, src/Hooks/useProgessBar.ts, src/Lib/FilesService.ts, src/Lib/constants.ts, yarn.lock
[Internal link](https://app.asana.com/0/1200588672119490/1202190286583003)
=> feat: show progress on file upload and download

ios/StandardNotes.xcodeproj/project.pbxproj, src/AppStack.tsx, src/ModalStack.tsx, src/Screens/Settings/Sections/FilesSection.styled.tsx, src/Screens/Settings/Sections/FilesSection.tsx, src/Screens/Settings/Settings.tsx, src/Screens/SideMenu/NoteSideMenu.tsx
[Internal link](https://app.asana.com/0/1200588672119490/1202213315870786)
=> feat: show files quota in preferences section

package.json, src/Screens/SideMenu/Files.styled.ts, src/Screens/SideMenu/Files.tsx, src/Screens/SideMenu/NoteSideMenu.tsx
[Internal link](https://app.asana.com/0/1200588672119490/1202294348118949)
=> feat: show "Learn more" in Files section if user is not entitled to files
