src/screens/SideMenu/MainSideMenu.js
src/screens/SideMenu/SideMenuCell.js

Original issue: https://github.com/standardnotes/mobile/issues/180
As discussed: https://github.com/standardnotes/bounties/issues/41
This adds the checks for "no_mobile" in the package_info that when set to true will prevent the theme from being activated with a prompt (as shown below). The "My No Distraction" theme is a self hosted theme so I could change the package_info to include the no_mobile data.

Prevent desktop only themes from being activated

---

src/screens/Notes/Notes.js

When this Notes component regains focus we want to make sure to reload Tablet State to ensure the MainSideMenu is accessible again and doesn't remain locked. During authentication (namely FaceID on iOS), the componentWillBlur and componentWillFocus events would sometimes cause a race condition that would result in a locked MainSideMenu. When this Notes component regained focus, the MainSideMenu would remain locked.
Related: https://github.com/standardnotes/mobile/issues/186

Fixes race condition for empty locked MainSideMenu

---

src/lib/ApplicationState.js
src/screens/Root.js
src/style/StyleKit.js

Adds a small icon on the left side of the compose window that allows the toggling of the sidebar note list. 
This even accounts for when the keyboard pops up and covers the little icon (making you unable to collapse the sidebar) it will move the icon up to sit on top of the keyboard so that you can still toggle it while writing. This is particularly helpful in landscape.

Adds a button to toggle Note sidebar in tablet mode

---

src/screens/Compose.js

This should fix iPad issues by remounting the compose plain editor when the note is changing. #248

fix: remount compose view when note changes

---

src/lib/installation_service.ts

I am aware we wanted to use namespace keychain, but this is not working as expected - the new installation will not have a legacy identifier and that means it will not discover that there is a keychain value. Until we have multiple accounts it has to stay like this.

fix: reinstall wipe

---

src/lib/component_manager.ts

Some 3rd party themes are not applied correctly on the component view of the mobile app. The reason is that when fetching the stylesheet, the Sass variables are extracted and placed into `mobileContent.variables`. This is then passed to the component view, but other CSS style rules from said stylesheet are not included.
Take as an example the [Tangerine theme](https://github.com/shompoe/sn-tangerine-theme). The CSS stylesheet is located [here](https://github.com/shompoe/sn-tangerine-theme/blob/master/dist/dist.css). The stylesheet contains the variables for `sn-stylekit`. Additionally, it contains rules to change the look of some editors (see [line 108](https://github.com/shompoe/sn-tangerine-theme/blob/691026b6e908f89989458d066c387809d5608ccb/dist/dist.css#L108)):
```css
...
.CodeMirror …
```

fix: theme urls should be passed as-is to components

---

README.md

An updated app will be available on F-Droid in the future. Its progress can be tracked [here](https://github.com/standardnotes/mobile/issues/292).

docs: remove link to the outdated apk on F-Droid

---

package.json
src/App.tsx
src/ModalStack.tsx
src/lib/application.ts
src/lib/application_state.ts
src/screens/Authenticate/Authenticate.tsx
yarn.lock

Fix biometrics always showing even when set to on quit bug. Reverted previous approach. Added previouslyLaunched static variable to MobileApplication, overrode SNJS getLaunchChallenge method and when app has been previously launched and biometrics timing is set to on quit, filtered out biometrics from the challenge prompts array.

Fix biometrics on quit

---

src/screens/Compose/Compose.tsx

The wording in these alerts seemed to be on a TODO state. Updated to more user-friendly texts, but wanted to open this to feedback for the right wording.

fix: save note alerts wording

---

ios/Podfile.lock
package.json
src/screens/Compose/ComponentView.tsx
src/screens/Compose/Compose.styled.ts
src/screens/Compose/Compose.tsx
yarn.lock

- Added react-native-zip-archive-dependency
- Added offline editors feature. Editor's zip file is downloaded and extracted. Zip files are deleted after extraction to save up space. If there's a new version of an editor, it's downloaded and the previous version's files are deleted. If there is an error with downloading/loading the offline editor, it should fallback to loading the online editor.
- Changed loading editor text to "Downloading/Loading [editor]..."
Some issues to fix (WIP):
- Some editors look zoomed out when loaded from offline source
- There's a small time gap between the "Downloading..." and the "Loading..." message

feat: offline editors

---

src/screens/Compose/Compose.tsx

Currently editors aren't being removed from the editor group when unmounting the compose screen, which broke the `useHasEditor` hook and subsequently the side drawer that would rely on this hook to determine whether to lock itself or not

fix: close editor when unmounting compose component

---

package.json
src/screens/Compose/ComponentView.tsx
src/screens/Compose/Compose.tsx
yarn.lock

Kept the timeout which should handle removing the message after 200ms if the ThemesActivated action hasn't fired before that. Increased the downloading editor message to 200ms to prevent the minor "skipping" from the downloading to the loading message.

feat: remove editor loading message on ThemesActivated action

---

src/screens/Compose/ComponentView.tsx

Potential fix for removeObserver is undefined errors (liveItem deinit being called more than once).

fix: live item deinit called more than once

---

android/build.gradle
package.json
yarn.lock

React Native versions are tied to specific React version (those are synced by Facebook). Using another version is not recommended.
Also updated gradle build tools. For more streamlined upgrade experience you can use https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.1

fix: downgrade react to officially supported version

---

ios/StandardNotes/Info.plist
ios/StandardNotesDev-Info.plist

The Standard Notes app on iOS throws the following, when using the camera to scan a QR code for the TokenVault extension:
`Termination Reason: TCC, This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.`
- adds `NSCameraUsageDescription` description
- adds `NSPhotoLibraryUsageDescription` description
Maybe we want to keep descriptions generic for other use cases. Thoughts @mobitar ?
---
should fix https://github.com/standardnotes/token-vault/issues/15

fix: usage description for camera and photos (iOS)

---

src/screens/Settings/Sections/OptionsSection.tsx

- fixes an issue where importing a backup file from web/desktop does not work and throws the error `Unable to open file. Ensure it is a proper JSON file and try again.`

fix: import file on iOS

---

ios/Podfile.lock
package.json
src/screens/Compose/ComponentView.tsx
src/screens/Compose/Compose.tsx
src/types/react-native-static-server/index.d.ts
yarn.lock

This is a POC for serving offline editors from a local static server and accessing them through the HTTP protocol on the WebView, instead of using the file protocol.
The issue when using the file protocol is the WebView disallows running web workers, which some editors use. The Bold Editor for example uses FileSafe which in turn uses web workers to encrypt/decrypt attachments.
By doing this, we'd be creating a local server (accessible only by the app and not from outside of it) serving the editors which can then be accessed through a URL, just like online editors. This fixes the following issues for offline editors reported so far (and probably other potential issues related to the same cause):
- Bold Editor can't encrypt/decrypt attachments
- Plus Editor doesn't show embedded videos

feat: serve offline editors from local static server

---

src/lib/application.ts

A trailing slash (`/`) causes the dev app to throw an "Unknown error" when performing sign in/register requests. 
Btw, we should consider parsing the `defaultHost` URL to remove any trailing slashes `snjs`

fix: remove trailing slash on defaultHost url

---

src/screens/Compose/Compose.tsx

Asana task: https://app.asana.com/0/1199914526147392/1199625073300525

fix: show editor name when editor fails to load

---

src/lib/backups_service.ts

(Asana tasks: https://app.asana.com/0/1199914526147392/1201318023371010)

fix: when exporting via Email, use `Base64.encode` for URL safe stringified data

---

package.json
yarn.lock

Install `react-native-sodium` package with the specific commit

fix: use specific commit for the package (working version)

---

src/lib/react_native_crypto.ts

Otherwise it gives an exception (more details [here](https://github.com/tectiv3/react-native-aes/issues/60#issuecomment-989124984))

fix: import Aes from NativeModules

---

src/screens/SideMenu/Files.styled.ts
src/screens/SideMenu/Files.tsx
src/screens/SideMenu/SideMenuCell.tsx
src/screens/SideMenu/SideMenuSection.tsx

[Internal link](https://app.asana.com/0/1199942776723820/1202138269476662)

fix: don't wrap multi-line file names after some actions (such as detaching from note)

---

src/Hooks/useFiles.ts
src/Lib/FilesService.ts
src/ModalStack.tsx
src/Screens/SideMenu/Files.tsx
src/Screens/UploadedFilesList/UploadedFileItem.styled.ts
src/Screens/UploadedFilesList/UploadedFileItem.tsx
src/Screens/UploadedFilesList/UploadedFilesList.tsx

Internal links: [#1](https://app.asana.com/0/1201653402817596/1202178314278387), [#2](https://app.asana.com/0/1201653402817596/1202178702318663), [#3](https://app.asana.com/0/1201653402817596/1202178702318665)
- Don't truncate file list in note side menu
- Files screen is not themed properly with dark themes
- Tap selection on file should trigger preview; long press should show action sheet
- Files should be sorted by name

fix: don't truncate files list in note side menu
